// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaL53kiJfrdlH5jNaoBBnCcDv10FZ82z0',
    appId: '1:270397286111:web:ce2ed98b5a57b589dbeb6a',
    messagingSenderId: '270397286111',
    projectId: 'centifygames-f547e',
    authDomain: 'centifygames-f547e.firebaseapp.com',
    storageBucket: 'centifygames-f547e.appspot.com',
    measurementId: 'G-DSSL2BS1M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAANrT5DbknTE4zD50y5xyIqbksXTkBNbI',
    appId: '1:270397286111:android:1ca278888cf3ee1fdbeb6a',
    messagingSenderId: '270397286111',
    projectId: 'centifygames-f547e',
    storageBucket: 'centifygames-f547e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJnYY4hcP_szAEsF52V5DQXkX-xAbsRMg',
    appId: '1:270397286111:ios:024b719a99e25c40dbeb6a',
    messagingSenderId: '270397286111',
    projectId: 'centifygames-f547e',
    storageBucket: 'centifygames-f547e.appspot.com',
    iosClientId: '270397286111-aijv4rpckncfi4k2g70u73ptomejurq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.web',
  );
}
